// SPDX-License-Identifier: MIT

/// \file
/// \brief packing and construction of dynamic segment
/// \copyright Copyright (C) 2026 Frank Secilia

#pragma once

#include <crv/lib.hpp>
#include <crv/algorithm.hpp>
#include <crv/math/fixed/fixed.hpp>
#include <crv/math/fixed/float_conversions.hpp>
#include <crv/math/float_extraction.hpp>
#include <crv/math/integer.hpp>
#include <crv/math/polynomial.hpp>
#include <crv/math/shifter.hpp>
#include <crv/math/spline/construction/function_sampler.hpp>
#include <crv/math/spline/segment.hpp>
#include <algorithm>
#include <climits>

namespace crv::spline {

// --------------------------------------------------------------------------------------------------------------------
// packing
// --------------------------------------------------------------------------------------------------------------------

template <typename t_packed_field_t> struct field_packer_t
{
    using packed_field_t = t_packed_field_t;

    template <typename unpacked_field_t, typename field_layout_t>
    constexpr auto operator()(unpacked_field_t unpacked_field, field_layout_t layout) const noexcept -> packed_field_t
    {
        auto const packed_mantissa = static_cast<packed_field_t>(unpacked_field.mantissa) << layout.shift_width;
        auto const packed_shift = unpacked_field.shift & layout.shift_mask();

        auto const packed_field = packed_field_t{packed_mantissa | packed_shift};
        // assert(field_unpacker_t{}(packed_field, layout) == unpacked_field);

        return packed_field;
    }
};

template <typename shift_t> struct shift_solver_t
{
    struct solved_shift_t
    {
        shift_t accumulator_shift;
        shift_t coeff_shift;
        int_t next_exponent;
    };

    constexpr auto operator()(int_t accumulator_exponent, int_t next_exponent, int_t t_to_x_shift) const noexcept
        -> solved_shift_t
    {
        auto const relative_shift = next_exponent - accumulator_exponent;

        return {.accumulator_shift = t_to_x_shift + std::max<int_t>(0, relative_shift),
            .coeff_shift = std::max<int_t>(0, -relative_shift),
            .next_exponent = std::max(accumulator_exponent, next_exponent)};
    }
};

template <typename unpacked_field_t, auto shifter = shifter_t<>{}> struct relative_aligner_t
{
    using mantissa_t = unpacked_field_t::mantissa_t;

    struct relative_field_t
    {
        unpacked_field_t unpacked_field;
        mantissa_t next_mantissa;
    };

    static constexpr auto accumulator_width = int_t{sizeof(mantissa_t) * CHAR_BIT} - is_signed_v<mantissa_t>;

    constexpr auto operator()(mantissa_t accumulator, mantissa_t next, auto const& solved_shift) const noexcept
        -> relative_field_t
    {
        using shift_t = unpacked_field_t::mantissa_t;

        // flush out-of-scale terms
        auto const accumulator_mantissa = (solved_shift.accumulator_shift >= accumulator_width) ? 0 : accumulator;
        auto const accumulator_shift
            = (solved_shift.accumulator_shift >= accumulator_width) ? 0 : solved_shift.accumulator_shift;
        auto const next_mantissa
            = (solved_shift.coeff_shift >= accumulator_width) ? 0 : shifter.shr(next, solved_shift.coeff_shift);

        return relative_field_t{
            .unpacked_field = {
                .mantissa = accumulator_mantissa,
                .shift = int_cast<shift_t>(accumulator_shift),
            },
            .next_mantissa = next_mantissa
        };
    }
};

template <typename unpacked_field_t, typename shift_t, auto align_exponent> struct radix_aligner_t
{
    template <typename scaled_int_t>
    constexpr auto operator()(scaled_int_t const& accumulator, int_t radix) const noexcept -> unpacked_field_t
    {
        auto const exponent_aligned = align_exponent(scaled_int_t{
            .mantissa = accumulator.mantissa, .exponent = int_cast<shift_t>(accumulator.exponent + radix)});

        return unpacked_field_t{
            .mantissa = exponent_aligned.mantissa,
            .shift = int_cast<shift_t>(-exponent_aligned.exponent),
        };
    }
};

// this only takes log2_min_width for an assert; it should move to an enclosing type

template <typename packed_segment_t, typename float_extractor_t, typename shift_solver_t, typename relative_aligner_t,
    typename field_packer_t, typename radix_aligner_t, int_t in_frac_bits, int_t out_frac_bits, int_t log2_min_width,
    segment_layout_t segment_layout>
struct segment_packer_t
{
    using scaled_int_t = float_extractor_t::scaled_int_t;
    using scalar_t = float_extractor_t::scalar_t;
    using cubic_t = cubic_t<scalar_t>;

    // This condition is what prevents horner's loop intermediates from overflowing. If this assert ever pops, the
    // horner's loop generated by this packer will also be broken.
    static_assert(in_frac_bits + log2_min_width >= 0);

    [[no_unique_address]] float_extractor_t extract_float;
    [[no_unique_address]] shift_solver_t solve_shift;
    [[no_unique_address]] relative_aligner_t align_relative;
    [[no_unique_address]] field_packer_t pack_field;
    [[no_unique_address]] radix_aligner_t align_radix;

    constexpr auto operator()(cubic_t const& cubic, int_t log2_width) const noexcept -> packed_segment_t
    {
        auto packed_segment = packed_segment_t{};

        // skip zero prefix
        auto const seed_it = std::ranges::find_if(cubic, [](auto const& c) { return c != 0.0; });

        // handle degenerate cubics
        if (seed_it == cubic.end()) return packed_segment;

        auto const t_to_x_shift = in_frac_bits + log2_width;
        auto accumulator = extract_float(*seed_it);

        auto field_index = static_cast<int_t>(std::distance(cubic.begin(), seed_it));
        for (; field_index < fields_per_segment - 1; ++field_index)
        {
            auto const next_term = extract_float(cubic[field_index + 1]);

            // zero mantissa can't dominate scale; feed the solver the acc's exponent instead
            auto const effective_next_exp = (next_term.mantissa == 0) ? accumulator.exponent : next_term.exponent;

            // solve the relative scales
            auto const shift = solve_shift(accumulator.exponent, effective_next_exp, t_to_x_shift);

            // quantize the mantissas into fields
            auto const relative_field = align_relative(accumulator.mantissa, next_term.mantissa, shift);

            // update running state
            accumulator.mantissa = relative_field.next_mantissa;
            accumulator.exponent = shift.next_exponent;

            packed_segment[field_index] = pack_field(relative_field.unpacked_field, segment_layout.intermediate);
        }

        // finish final field
        packed_segment[fields_per_segment - 1]
            = pack_field(align_radix(accumulator, out_frac_bits), segment_layout.final);

        return packed_segment;
    }
};

/// creates final segment from its cubic and width
template <typename t_segment_t, typename segment_packer_t> struct segment_factory_t
{
    using segment_t = t_segment_t;

    using cubic_t = segment_packer_t::cubic_t;

    [[no_unique_address]] segment_packer_t pack_segment;

    constexpr auto operator()(cubic_t const& cubic, int_t log2_width) const noexcept -> segment_t
    {
        return segment_t{pack_segment(cubic, log2_width)};
    }
};

} // namespace crv::spline
