// SPDX-License-Identifier: MIT

/// \file
/// \brief packing and construction of dynamic segment
/// \copyright Copyright (C) 2026 Frank Secilia

#pragma once

#include <crv/lib.hpp>
#include <crv/algorithm.hpp>
#include <crv/math/fixed/fixed.hpp>
#include <crv/math/fixed/float_conversions.hpp>
#include <crv/math/float_extraction.hpp>
#include <crv/math/integer.hpp>
#include <crv/math/polynomial.hpp>
#include <crv/math/shifter.hpp>
#include <crv/math/spline/construction/function_sampler.hpp>
#include <crv/math/spline/segment.hpp>
#include <algorithm>
#include <climits>
#include <utility>

namespace crv::spline {

// --------------------------------------------------------------------------------------------------------------------
// packing
// --------------------------------------------------------------------------------------------------------------------

struct field_packer_t
{
    constexpr auto operator()(unpacked_field_t unpacked_field, field_layout_t layout) const noexcept -> packed_field_t
    {
        auto const packed_mantissa = static_cast<packed_field_t>(unpacked_field.mantissa) << layout.shift_width;
        auto const packed_shift = unpacked_field.shift & layout.shift_mask();

        auto const packed_field = packed_field_t{packed_mantissa | packed_shift};
        assert(field_unpacker_t{}(packed_field, layout) == unpacked_field);

        return packed_field;
    }
};

template <is_fixed t_x_t, is_fixed t_y_t, typename t_scaled_int_t, auto align_exponent, auto shifter = shifter_t<>{}>
struct segment_builder_t
{
    using x_t = t_x_t;
    using y_t = t_y_t;
    using scaled_int_t = t_scaled_int_t;

    static constexpr auto in_frac_bits = t_x_t::frac_bits;
    static constexpr auto out_frac_bits = t_y_t::frac_bits;

    static constexpr auto accumulator_width = int_t{sizeof(mantissa_t) * CHAR_BIT};

    int_t t_to_dx_shift;
    scaled_int_t accumulator;

    constexpr auto push(scaled_int_t const& next) noexcept -> unpacked_field_t
    {
        assert(t_to_dx_shift >= 0);

        // zero mantissa can't dominate scale; treat it as matching accumulator
        auto const next_exponent = (next.mantissa == 0) ? accumulator.exponent : next.exponent;
        auto const exp_gap = next_exponent - accumulator.exponent;

        // t_to_dx_shift absorbs x bit-growth; exp_gap lifts the accumulator when the next coeff is larger
        auto const accumulator_shift = t_to_dx_shift + std::max<int_t>(0, exp_gap);
        auto const coeff_shift = std::max<int_t>(0, -exp_gap);

        // flush out-of-scale terms; shift >= 64 means the value is below the dominant term's ULP
        auto const adjusted_mantissa = (coeff_shift >= accumulator_width) ? 0 : shifter.shr(next.mantissa, coeff_shift);
        auto const final_accumulator_mantissa = (accumulator_shift >= accumulator_width) ? 0 : accumulator.mantissa;
        auto const final_accumulator_shift = (accumulator_shift >= accumulator_width) ? 0 : accumulator_shift;

        accumulator.mantissa = adjusted_mantissa;
        accumulator.exponent = std::max(accumulator.exponent, next_exponent);

        return unpacked_field_t{
            .mantissa = final_accumulator_mantissa,
            .shift = int_cast<shift_t>(final_accumulator_shift),
        };
    }

    constexpr auto finish() const&& noexcept -> unpacked_field_t
    {
        auto const exponent_aligned = align_exponent(scaled_int_t{
            .mantissa = accumulator.mantissa, .exponent = int_cast<shift_t>(accumulator.exponent + out_frac_bits)});

        return unpacked_field_t{
            .mantissa = exponent_aligned.mantissa,
            .shift = int_cast<shift_t>(-exponent_aligned.exponent),
        };
    }
};

template <typename t_builder_t> struct builder_factory_t
{
    using builder_t = t_builder_t;

    using scaled_int_t = builder_t::scaled_int_t;

    constexpr auto operator()(int_t t_to_dx_shift, scaled_int_t accumulator) const noexcept -> builder_t
    {
        return builder_t{.t_to_dx_shift = t_to_dx_shift, .accumulator = accumulator};
    }
};

template <typename t_float_extractor_t, typename t_field_packer_t, typename t_builder_factory_t, int_t in_frac_bits,
    int_t log2_min_width, segment_layout_t segment_layout>
struct segment_packer_t
{
    using float_extractor_t = t_float_extractor_t;
    using field_packer_t = t_field_packer_t;
    using builder_factory_t = t_builder_factory_t;
    using segment_builder_t = builder_factory_t::builder_t;

    using scaled_int_t = float_extractor_t::scaled_int_t;
    using scalar_t = float_extractor_t::scalar_t;
    using cubic_t = cubic_t<scalar_t>;

    // This condition is what prevents horner's loop intermediates from overflowing. If this assert ever pops, the
    // horner's loop generated by this packer will also be broken.
    static_assert(in_frac_bits + log2_min_width >= 0);

    [[no_unique_address]] field_packer_t pack_field;
    [[no_unique_address]] float_extractor_t extract_float;
    [[no_unique_address]] builder_factory_t make_builder;

    constexpr auto operator()(cubic_t const& cubic, int_t log2_width) const noexcept -> packed_segment_t
    {
        auto packed_segment = packed_segment_t{};

        // skip zero prefix
        auto const seed_it = std::ranges::find_if(cubic, [](auto const& c) { return c != 0.0; });

        // handle degenerate cubics
        if (seed_it == cubic.end()) return packed_segment;

        // seed
        auto const t_to_dx_shift = in_frac_bits + log2_width;
        auto const seed = extract_float(*seed_it);
        auto builder = make_builder(t_to_dx_shift, seed);

        // process intermediate suffix
        auto field_index = static_cast<int_t>(std::distance(cubic.begin(), seed_it));
        for (; field_index < fields_per_segment - 1; ++field_index)
        {
            auto const scaled_int = extract_float(cubic[field_index + 1]);
            packed_segment[field_index] = pack_field(builder.push(scaled_int), segment_layout.intermediate);
        }

        // finish final field
        packed_segment[fields_per_segment - 1] = pack_field(std::move(builder).finish(), segment_layout.final);

        return packed_segment;
    }
};

/// creates final segment from its cubic and width
template <typename t_segment_t, typename t_segment_packer_t> struct segment_factory_t
{
    using segment_t = t_segment_t;
    using segment_packer_t = t_segment_packer_t;

    using scalar_t = segment_packer_t::scalar_t;
    using cubic_t = segment_packer_t::cubic_t;
    using function_sample_t = function_sample_t<scalar_t>;

    [[no_unique_address]] segment_packer_t pack_segment;

    constexpr auto operator()(cubic_t const& cubic, int_t log2_width) const noexcept -> segment_t
    {
        return segment_t{pack_segment(cubic, log2_width)};
    }
};

} // namespace crv::spline
