# SPDX-License-Identifier: GNU
# Copyright (c) 2025 Frank Secilia

KERNEL_GE_6_11 := $(shell expr $(VERSION) \* 1000 + $(PATCHLEVEL) \>= 6011)
ifneq ($(KERNEL_GE_6_11),1)
$(error curves requires kernel 6.11+)
endif

obj-m := curves.o

curves-common-objs := \
  fixed.o \
  input_shaping.o \
  kernel_compat.o \
  math.o

curves-driver-objs := entry_point.o spline.o

curves-objs := $(curves-common-objs) $(curves-driver-objs)

# Compose module version string from actual version and git hash.
include $(src)/version.mk
CURVES_GIT_HASH := \
  $(shell git rev-parse --short HEAD 2>/dev/null || echo "standalone")
CURVES_MODULE_VERSION := "$(CURVES_VERSION)-$(CURVES_GIT_HASH)"
ccflags-y += -DCURVES_MODULE_VERSION="\"$(CURVES_MODULE_VERSION)\""
