#include "main_window.hpp"

// This is the C++ header file generated by the
// User Interface Compiler (uic) from your .ui file.
// CMake will handle generating this file automatically.
#include "ui_main_window.h"

// Constructor
MainWindow::MainWindow(QWidget* parent)
    // Call the parent class constructor
    : QMainWindow(parent),
      // Create the instance of our UI class
      ui_(std::make_unique<Ui::MainWindow>()) {
  // This is the line that actually creates and lays out
  // all the widgets from main_window.ui onto this window.
  ui_->setupUi(this);

  // You can now access any widget you named in Designer, e.g.:
  // ui_->myButton->setText("Hello!");
  // (We'll add buttons in the next step)
}

// Destructor
// This empty definition must be in the .cpp file where
// Ui::MainWindow is a complete type (because we included
// ui_main_window.h here).
MainWindow::~MainWindow() = default;
