# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Frank Secilia
#
# defines project-wide build settings

#
# Standard Build Settings
#

# c++ standard
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
set(CMAKE_CXX_EXTENSIONS TRUE)
set(CMAKE_CXX_SCAN_FOR_MODULES FALSE)

# visibility
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN TRUE)
set(CMAKE_POSITION_INDEPENDENT_CODE TRUE)

# lto
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE TRUE)
