// SPDX-License-Identifier: MIT

/// \file
/// \brief fixed point fast rsqrt
///
/// # Definition
///
/// This module solves `y = 1/sqrt(x)` over the domain `x > 0` using Newton-Raphson. We define a function, `f(y)`, with
/// the same roots as y, start with an initial guess near the solution, then iterate using the recurrence relation:
///
///     `y_{n+1} = y_n - f(y_n)/f'(y_n)`
///
/// Each step finds the line tangent to `f(y_n)`, finds the horizontal intercept of that tangent, then repeats with
/// `y_{n+1}` set to that intercept. With a good initial guess for `y_0`, this converges quadratically to the root of
/// `f(y)`.
///
/// # Derivation
///
/// In the case of `y = 1/sqrt(x)`, we choose `f(y) = y^-2 - x`:
///
///     ```
///        y = 1/sqrt(x)    [given]
///      y^2 = 1/x          [square both sides]
///     xy^2 = 1            [multiply both sides by x]
///        x = y^-2         [divide both sides by y^2]
///        0 = y^-2 - x     [find root]
///     ```
///
/// There are other choices, but this has an important property. Given `f'(y) = -2y^-3`:
///
///     ```
///     y_{n+1} = y_n - f(y_n)/f'(y_n)             [original]
///             = y_n - (y_n^-2 - x)/(-2y_n^-3)    [substitute functions]
///             = y_n + y_n^3(y_n^-2 - x)/2        [multiply right by -y_n^3/-y_n^3]
///             = y_n + y_n(1 - xy_n^2)/2          [distribute y_n^2]
///             = y_n(1 + (1 - xy_n^2)/2)          [factor out common y_n]
///             = y_n(3 - xy_n^2)/2                [combine constants]
///     ```
///
/// This form allows calculating rsqrt using only multiplication, subtraction, and a shift.
///
/// # Convergence
///
/// We choose to characterize the error multiplicatively using `(1/sqrt(x))(1 - e_n)`. There are other choices, but this
/// makes the algebra straightforward:
///
///     ```
///                 y_n = (1/sqrt(x))(1 - e_n)                       [definition]
///               y_n^2 = (1/x)(1 - e_n)^2                           [square both sides]
///             x*y_n^2 = (1 - e_n)^2                                [multiply by x]
///                     = 1 - 2e_n + e_n^2                           [expand]
///         3 - x*y_n^2 = 2 + 2e_n - e_n^2                           [subtract from 3]
///     (3 - x*y_n^2)/2 = 1 + e_n - e_n^2/2                          [divide by 2]
///             y_{n+1} = y_n(1 + e_n - e_n^2/2)                     [NR recurrence]
///                     = (1/sqrt(x))(1 - e_n)(1 + e_n - e_n^2/2)    [sub y_n]
///     ```
/// Expanding (1 - e_n)(1 + e_n - e_n^2/2):
///
///     ```
///     (1 - e_n)(1 + e_n - e_n^2/2) = (1 - e_n)1 + (1 - e_n)e_n - (1 - e_n)e_n^2/2    [distribute (1 - e_n)]
///                                  = 1 + e_n - e_n^2/2 - e_n - e_n^2 + e_n^3/2       [distribute (1 - e_n)]
///                                  = 1 - 3e_n^2/2 + e_n^3/2                          [combine like terms]
///                                  = 1 - e_n^2(3 - e_n)/2                            [factor out common e_n^2]
///     ```
///
/// So `y_{n+1} = (1/sqrt(x))(1 - e_n^2(3 - e_n)/2)`:
///
///     ```
///         y_{n+1} = (1/sqrt(x))(1 - e_{n+1})             [definition]
///         y_{n+1} = (1/sqrt(x))(1 - e_n^2(3 - e_n)/2)    [derived]
///
///     1 - e_{n+1} = 1 - e_n^2(3 - e_n)/2    [given]
///        -e_{n+1} = -e_n^2(3 - e_n)/2       [subtract 1 from both sides]
///         e_{n+1} = e_n^2(3 - e_n)/2        [negate]
///     ```
///
/// For small `|e_n|`, `(3 - e_n) ~= 3`, so `e_{n+1} ~= 1.5e_n^2`. This is why a good initial guess converges
/// quadratically.
///
/// # Initial Guess
///
/// The initial guess is found using a quadratic minimax approximation of `1/sqrt(x)` using Horner's method:
///
///     `C0 + -C1*x + C2*x^2 = C0 - x*(C1 - x*C2)`.
///
/// The coefficients are generated by Sollya over the domain [0.5, 1.0) in unsigned Q2.62.
///
/// Using a quadratic approximation balances Horner iterations against Newton-Raphson iterations. Each NR iteration uses
/// 3 multiplies. Horner iterations use 1. For the same precision, a -log2/2 approximation requires 6 NR iterations.
/// Linear requires 4. Quadratic requires 3. Cubic also requires 3, but is more expensive to evaluate than quadratic, so
/// we use quadratic.
///
/// Budget 3 narrowings per iteration, then add a constant slack of 2. Truncation error for iteration i is 3i + 2. With
/// the quadratic approximation, the worst case error becomes noise-limited after 3 iterations, dropping below the
/// fixed-point rounding floor:
///
///     iterations | approximation error (ulps) | truncation error(ulps) | max error (ulps)
///         1      |     101527141262302        |            5           | 101527141262302
///         2      |          3352684267        |            8           |      3352684267
///         3      |                   4        |           11           |              11
///         4      |                   1        |           14           |              14
///
/// # Newton-Raphson
///
/// NR iteration is performed in the reduced range [0.5, 1.0). Range reduction uses clz to normalize the input to this
/// range. Restoration rescales the result back to the original range.
///
/// \copyright Copyright (C) 2026 Frank Secilia

#pragma once

#include <crv/lib.hpp>
#include <crv/math/fixed/fixed.hpp>
#include <crv/math/fixed/fma.hpp>
#include <crv/math/limits.hpp>
#include <crv/math/shifter.hpp>
#include <array>
#include <bit>

namespace crv {

namespace rsqrt_initial_guesses {

/// uses a quadratic minimax approximation of 1/sqrt(x) to find the initial guess over the range [0.5, 1).
struct quadratic_minimax_t
{
    using in_t    = fixed_t<uint64_t, 64>;
    using coeff_t = fixed_t<uint64_t, 62>;
    using out_t   = coeff_t;

    // quadratic approximation coefficients
    //
    // The constants are in Q2.62, so they're scaled by 2^62 and rounded. They're generated using sollya.
    // See tools/sollya/gen_rsqrt_initial_guess.sollya.
    static constexpr auto coeffs = std::array{
        coeff_t::literal(10354071711462988194ULL),
        coeff_t::literal(9674659108971248202ULL),
        coeff_t::literal(3949952137299739940ULL),
    };

    // \pre in must be in [0.5, 1)
    static constexpr auto operator()(in_t in) noexcept -> out_t
    {
        // upper bound is automatic since 1.0 is unrepresentable in unsigned Q0.64, but lower bound must be checked
        [[maybe_unused]] constexpr auto half = in_t::literal(1ULL << (in_t::frac_bits - 1));
        assert(in >= half);

        // apply horner's method: C0 + -C1*x + C2*x^2 = C0 - x*(C1 - x*C2)
        auto const inner = coeff_t::convert(multiply(in, coeffs[2]));
        auto const outer = coeff_t::convert(multiply(in, coeffs[1] - inner));
        return coeffs[0] - outer;
    }
};

} // namespace rsqrt_initial_guesses

/// reciprocal sqrt over the range [0.5, 1), taking Q0.64 and returning Q66.62.
///
/// This type represents the inner portion of the rsqrt NR loop. It expects parameter in a specific Q-format and returns
/// results in a specific Q-format. The number of iterations and the algorithm for the initial guess are tunable
/// parameters
template <int_t nr_iteration_count = 3, typename initial_guess_t = rsqrt_initial_guesses::quadratic_minimax_t,
          typename shifter_t = shifter_t<rounding_modes::shr::truncate_t>>
    requires(nr_iteration_count > 0)
struct normalized_rsqrt_t
{
    using in_t  = fixed_t<uint64_t, 64>;
    using out_t = fixed_t<uint128_t, 62>;
    using nr_t  = initial_guess_t::coeff_t;

    using narrow_t = nr_t::value_t;

    static constexpr auto three = nr_t{3};

    [[no_unique_address]] initial_guess_t initial_guess{};

    // \pre in must be in [0.5, 1)
    constexpr auto operator()(in_t x, shifter_t shifter = shifter_t{}) const noexcept -> out_t
    {
        // Newton-Raphson
        auto y = initial_guess(x);
        for (int_t i = 0; i < nr_iteration_count - 1; ++i)
        {
            auto const yy      = nr_t::convert(multiply(y, y), shifter);
            auto const xyy     = nr_t::convert(multiply(x, yy), shifter);
            auto const product = multiply(y, three - xyy);
            y = nr_t::literal(int_cast<narrow_t>(shifter.template shr<nr_t::frac_bits + 1>(product.value)));
        }

        // Final iteration does not narrow at the end.
        auto const yy      = nr_t::convert(multiply(y, y), shifter);
        auto const xyy     = nr_t::convert(multiply(x, yy), shifter);
        auto const product = multiply(y, three - xyy);
        return out_t::literal(shifter.template shr<nr_t::frac_bits + 1>(product.value));
    }
};

/// reciprocal sqrt
template <is_fixed out_t, is_fixed in_t = out_t, typename normalized_rsqrt_t = normalized_rsqrt_t<>> struct rsqrt_t
{
    // 128-bit types are reserved for intermediates
    static_assert(sizeof(typename in_t::value_t) <= 8 && sizeof(typename out_t::value_t) <= 8);

    using nr_t     = normalized_rsqrt_t::nr_t;
    using x_norm_t = normalized_rsqrt_t::in_t;

    static constexpr auto x_frac_bits = in_t::frac_bits;
    static constexpr auto y_frac_bits = normalized_rsqrt_t::out_t::frac_bits;

    static constexpr auto sqrt2 = nr_t::literal(0x5A827999FCEF3242ULL);

    [[no_unique_address]] normalized_rsqrt_t normalized_rsqrt{};

    // \pre x > 0
    template <typename shifter_t = shifter_t<>>
    constexpr auto operator()(in_t x, shifter_t shifter = shifter_t{}) const noexcept -> out_t
    {
        assert(x.value > 0);

        // normalize x to [0.5, 1.0) in the format expected by normalized_rsqrt
        auto const x_lz            = std::countl_zero(x.value);
        auto const x_norm          = x_norm_t::literal(x.value << x_lz);
        auto const x_norm_exponent = x_lz + x_frac_bits;

        // apply normalized rsqrt
        auto y = normalized_rsqrt(x_norm);

        // denormalize
        auto const odd_exponent = (x_norm_exponent & 1) != 0;
        if (odd_exponent)
        {
            auto const y_narrow = nr_t::convert(y, shifter);
            y                   = normalized_rsqrt_t::out_t::convert(multiply(y_narrow, sqrt2), shifter);
        }

        auto const y_denorm_frac_bits = y_frac_bits + (x_norm_t::frac_bits >> 1) - (x_norm_exponent >> 1);
        auto const shift              = out_t::frac_bits - y_denorm_frac_bits;

        using wide_out_t  = fixed_t<uint128_t, out_t::frac_bits>;
        auto const result = wide_out_t::literal(shifter.shift(y.value, shift));
        return out_t::convert(result, shifter);
    }
};

} // namespace crv
